version: "3.7"
services:
  golang-api:
    image: golang:1.22.2
    working_dir: /app
    volumes:
      - ./:/app
    command: go run cmd/api/api.go
    ports:
      - 8054:8054
    networks:
      - services
    extra_hosts:
      - "host.docker.internal:host-gateway"

  golang-worker:
    image: golang:1.22.2
    working_dir: /app
    volumes:
      - ./:/app
    command: go run cmd/worker/worker.go
    networks:
      - services
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  pgdata:

networks:
  services:
    driver: bridge
